services:
  backend:
    container_name: diamond-shield-backend

    build:
      context: ./backend
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      APP_DEFAULT_ADMIN_USERNAME: ${DEFAULT_ADMIN_USERNAME}
      APP_DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD}

      APP_CORS_ALLOWED_ORIGIN_PATTERN: "http://*:[*]"

      TZ: Europe/Moscow

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      diamond-network:
        ipv4_address: 172.30.0.10

  frontend:
    container_name: diamond-shield-frontend

    build:
      context: ./frontend
      dockerfile: Dockerfile

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "80:80"

    networks:
      diamond-network:
        ipv4_address: 172.30.0.20

networks:
  diamond-network:
    name: diamond-shield-network

    ipam:
      config:
        - subnet: 172.30.0.0/24