server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: Diamond Shield - Lite

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/diamond_shield_lite_docker}
    username: ${SPRING_DATASOURCE_USERNAME:diamond}
    password: ${SPRING_DATASOURCE_PASSWORD:diamond}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true

  mvc:
    converters:
      preferred-json-mapper: gson

  servlet:
    multipart:
      max-file-size: 100KB
      max-request-size: 200KB

app:
  cors:
    allowed-origin-pattern: ${APP_CORS_ALLOWED_ORIGIN_PATTERN:http://*:[*]}

  default-admin:
    username: ${APP_DEFAULT_ADMIN_USERNAME:admin}
    password: ${APP_DEFAULT_ADMIN_PASSWORD:admin123}

logging:
  level:
    org.springframework.web.context.request.async: ERROR